version: '3.4'

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: SqlDB
    networks:
        - shared-network

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: Smtp
    volumes:
        - smtp4devvolume:/smtp4dev
    networks:
        - shared-network

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    container_name: Basket
    build:
      context: .
      dockerfile: APIs/BasketApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  billingapi:
    image: ${DOCKER_REGISTRY-}billingapi
    container_name: Billing
    build:
      context: .
      dockerfile: APIs/BillingApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  catalogueapi:
    image: ${DOCKER_REGISTRY-}catalogueapi
    container_name: Catalogue
    build:
      context: .
      dockerfile: APIs/CatalogueApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  emailapi:
    image: ${DOCKER_REGISTRY-}emailapi
    container_name: Email
    build:
      context: .
      dockerfile: APIs/EmailApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    container_name: Order
    build:
      context: .
      dockerfile: APIs/OrderApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  salesapi:
    image: ${DOCKER_REGISTRY-}salesapi
    container_name: Sales
    build:
      context: .
      dockerfile: APIs/SalesApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  shippingapi:
    image: ${DOCKER_REGISTRY-}shippingapi
    container_name: Shipping
    build:
      context: .
      dockerfile: APIs/ShippingApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  warehouseapi:
    image: ${DOCKER_REGISTRY-}warehouseapi
    container_name: Warehouse
    build:
      context: .
      dockerfile: APIs/WarehouseApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  shopwebsite.server:
    image: ${DOCKER_REGISTRY-}shopwebsiteserver
    container_name: ShopWebsite
    build:
      context: .
      dockerfile: websites/ShopWebsite/Dockerfile
    networks:
        - shared-network

  stockmanagementwebsite.server:
    image: ${DOCKER_REGISTRY-}stockmanagementserver
    container_name: StockManagementWebsite
    build:
      context: .
      dockerfile: websites/StockManagementWebsite/Dockerfile
    networks:
        - shared-network

volumes:
  sqlvolume:
    driver: local    
  smtp4devvolume:
    driver: local

networks:
  shared-network:
    driver: bridge
