version: '3.4'

services:
  sql-server-db:
    image: mcr.microsoft.com/mssql/server:latest
    networks:
        - shared-network

  smtp4dev:
    image: rnwood/smtp4dev
    networks:
        - shared-network

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: APIs/BasketApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  billingapi:
    image: ${DOCKER_REGISTRY-}billingapi
    build:
      context: .
      dockerfile: APIs/BillingApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  catalogueapi:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: APIs/CatalogueApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  emailapi:
    image: ${DOCKER_REGISTRY-}emailapi
    build:
      context: .
      dockerfile: APIs/EmailApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: APIs/OrderApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  salesapi:
    image: ${DOCKER_REGISTRY-}salesapi
    build:
      context: .
      dockerfile: APIs/SalesApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  shippingapi:
    image: ${DOCKER_REGISTRY-}shippingapi
    build:
      context: .
      dockerfile: APIs/ShippingApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  warehouseapi:
    image: ${DOCKER_REGISTRY-}warehouseapi
    build:
      context: .
      dockerfile: APIs/WarehouseApi/Dockerfile
    depends_on: 
        - sql-server-db
    networks:
        - shared-network

  shopwebsite.server:
    image: ${DOCKER_REGISTRY-}shopwebsiteserver
    build:
      context: .
      dockerfile: websites/Dockerfile
    networks:
        - shared-network

volumes:
  sqlvolume:
    driver: local    

networks:
  shared-network:
    driver: bridge
