version: '3.4'

services:
  sql-server-db:
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password1234!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    volumes:
        - sqlvolume:/var/opt/mssql

  smtp4dev:
    ports:
      - 3000:80
      - 2525:25

  basketapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=${DATABASE_STRING}
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  billingapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=${DATABASE_STRING}
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  catalogueapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=${DATABASE_STRING}
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  emailapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "80"

  orderapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=${DATABASE_STRING}
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  salesapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=${DATABASE_STRING}
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  shippingapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=${DATABASE_STRING}
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  warehouseapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Database=${DATABASE_STRING}
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  shopwebsite.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "65200:80"

  stockmanagementwebsite.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ApplicationInsights=${APP_INSIGHTS}
      - ConnectionStrings__ServiceBus=${SERVICEBUS_ENDPOINT}
    ports:
      - "65201:80"